---
- name: "add google's gpg key"
  apt_key: 
    url: "https://packages.cloud.google.com/apt/doc/apt-key.gpg" 
    state: present

- name: "add the google apt repository"
  apt_repository:
    repo: "deb http://packages.cloud.google.com/apt google-cloud-logging-wheezy main"
    state: present

- name: "install the google logging agent"
  apt:
    name:
      - google-fluentd
      - google-fluentd-catch-all-config
    state: present 
    update_cache: yes
